// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqljobjnyfmvnevzthxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbGpvYmpueWZtdm5ldnp0aHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDQzMjAsImV4cCI6MjA3MjQ4MDMyMH0.Kt_XLtu2z0SUtLTTkJKFpF6lQ2vG-zX5xZojXGV_peU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});